### ISSUE TITLE
Hidden selected words

### ISSUE THREAD

**Issue by LaRiffle** [rmarquet21/st-text-annotator#1]
Hey! Really like what you built 🙌 
I just noticed there is kind of a hidden state with words not displayed as highlighted even if they are in the output
<img width="843" alt="CleanShot 2023-11-24 at 11 40 36@2x" src="https://github.com/rmarquet21/st-text-annotator/assets/12446521/c756cfc7-7446-4873-a9f6-68a47d77d81f">

**Comment by rmarquet21** [comment]
Thanks for the feedback! I'll get right on it!

**Comment by rmarquet21** [comment]
@LaRiffle Can you be more precise about how you came up with the NULL values ? I can't reproduce them.

**Comment by LaRiffle** [comment]
To have the hidden state you can do the following : 
- Click on word Lorem
- Click on word Ipsum
- Click on button Add
- Click on work dolor
- Click on button Add
That's where you arrive:
<img width="779" alt="CleanShot 2023-12-06 at 14 53 29@2x" src="https://github.com/rmarquet21/st-text-annotator/assets/12446521/4a0994d0-dd0e-4d3f-98b8-e2adf535d4fe">

None seem related to deleted annotations
